/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicioyregistrase;

import Logica.CarritoManager;
import Logica.ProductoCarrito;
import javax.swing.JOptionPane;

/**
 *
 * @author xp30p
 */
public class fritura extends javax.swing.JFrame {

    /**
     * Creates new form fritura
     */
    public fritura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Chicharon = new javax.swing.JSpinner();
        bandeja = new javax.swing.JSpinner();
        orejita = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        batata = new javax.swing.JSpinner();
        frito = new javax.swing.JSpinner();
        yuca = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 630));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 0, 60, 64);

        jButton1.setText("Añadir al Carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(610, 580, 140, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pa'Freir Y Gozar");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 0, 370, 50);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carnes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 60, 150, 40);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Acompañamientos");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 320, 330, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chi.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(54, 108, 120, 108);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/orejita.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 110, 120, 108);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carnes2-removebg-preview.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 110, 114, 108);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Chicharron");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(54, 222, 70, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bandeja completa");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(330, 220, 110, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Orejitas de cerdo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(560, 220, 100, 16);
        jPanel1.add(Chicharon);
        Chicharon.setBounds(54, 272, 42, 22);
        jPanel1.add(bandeja);
        bandeja.setBounds(330, 270, 41, 22);
        jPanel1.add(orejita);
        orejita.setBounds(560, 270, 42, 22);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/batata-removebg-preview.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 370, 120, 108);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ttd1.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 370, 121, 108);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/yuca1.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(520, 370, 120, 108);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Batata Frita");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(50, 480, 70, 16);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Tostones");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(350, 480, 60, 16);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("yuca");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(560, 480, 40, 16);
        jPanel1.add(batata);
        batata.setBounds(50, 530, 46, 22);
        jPanel1.add(frito);
        frito.setBounds(350, 530, 45, 22);
        jPanel1.add(yuca);
        yuca.setBounds(560, 530, 44, 22);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(0, -30, 780, 690);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // Ejemplo: Chicharrón
   int cantidad = (int) Chicharon.getValue();
    if (cantidad > 0) {
        CarritoManager.agregarProducto(new ProductoCarrito("Chicharrón", cantidad, 100.0));
    }

    // Ejemplo: Batata Frita
    int cantidadBatata = (int) batata.getValue();
    if (cantidadBatata > 0) {
        CarritoManager.agregarProducto(new ProductoCarrito("Batata frita", cantidadBatata, 100.0));
    }
    
    int cantidadbandeja = (int) bandeja.getValue();
    if (cantidadbandeja > 0) {
        CarritoManager.agregarProducto(new ProductoCarrito("Bandeja", cantidadbandeja, 2500.0));
    }
    
    int cantidadfrito = (int) frito.getValue();
    if (cantidadBatata > 0) {
        CarritoManager.agregarProducto(new ProductoCarrito("frito", cantidadBatata, 100.0));
    }
    
    int cantidadyuca = (int) yuca.getValue();
    if (cantidadyuca > 0) {
        CarritoManager.agregarProducto(new ProductoCarrito("Orejita", cantidadyuca, 100.0));
    }
    
    int cantidadorejita = (int) orejita.getValue();
    if (cantidadorejita > 0) {
        CarritoManager.agregarProducto(new ProductoCarrito("Orejita", cantidadBatata, 200.0));
    }

    // Agrega lo mismo para los demás productos...

    JOptionPane.showMessageDialog(this, "Productos agregados al carrito.");

    // Agrega lo mismo para los demás productos...

    JOptionPane.showMessageDialog(this, "Productos agregados al carrito.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fritura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fritura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fritura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fritura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fritura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Chicharon;
    private javax.swing.JSpinner bandeja;
    private javax.swing.JSpinner batata;
    private javax.swing.JSpinner frito;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner orejita;
    private javax.swing.JSpinner yuca;
    // End of variables declaration//GEN-END:variables
}
